name: Render and Upload RMarkdown

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for TinyTeX
        run: |
         sudo apt-get update
         sudo apt-get install -y libglpk-dev
         
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::tinytex
            any::aws.s3
            
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install tinytex
        run: Rscript -e 'tinytex::install_tinytex()'
         
      - name: Render RMarkdown
        run: |
          rmarkdown::render('docs/banner_test.Rmd', output_format = "pdf_document")
        shell: Rscript {0}
        
      - name: Upload to Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          Rscript -e "aws.s3::put_object(file = 'docs/banner_test.pdf', object = 'banner_test.pdf', bucket = 'rfc-conditions/gw_forecasting', region = "", acl = "public-read")"
